version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://jonar:1234@db:5432/challenge
    restart: on-failure
    entrypoint: /dbMigrationAndSeed.sh
    #command: sleep 5 && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && tail -f /dev/null
  db:
    image: postgres
    environment:
      - POSTGRES_USER=jonar
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=challenge
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  db-data:
